name: more
version: 1.3.2
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/dart-more
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://jenkins.lukas-renggli.ch/job/dart-more/javadoc
dev_dependencies:
  browser: '>=0.10.0 <0.12.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  unittest: '>=0.10.0 <0.12.0'
