name: more
version: 0.5.8
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/MoreDart
dev_dependencies:
  browser: '>=0.5.0'
  junitconfiguration: '>=0.5.0'
  unittest: '>=0.5.0'
