name: more
version: 0.5.19
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/MoreDart
dependencies:
  meta: '>=0.7.0'
dev_dependencies:
  browser: '>=0.7.0'
  junitconfiguration: any
  unittest: '>=0.7.0'
