name: more
version: 1.5.0
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/dart-more
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.1 <0.13.0'
