name: more
version: 0.5.17
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/MoreDart
dependencies:
  meta: any
dev_dependencies:
  browser: any
  junitconfiguration: any
  unittest: any
