name: more
version: 1.0.4
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/MoreDart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
  unittest: '>=0.9.0 <0.10.0'
