name: more
version: 1.5.1
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/dart-more
environment:
  sdk: ^1.8.0
dev_dependencies:
  test: ^0.12.0