name: more
version: 0.5.2
author: Lukas Renggli <renggli@gmail.com>
description: More Dart — Literally
homepage: https://github.com/renggli/MoreDart
dev_dependencies:
  junitconfiguration: '>=0.4.7'
  unittest: '>=0.4.7'
